Create a Simple Neural Network in Python from Scratch

https://www.youtube.com/watch?v=kft1AJ9WVDk&t=699s

https://medium.com/technology-invention-and-more/how-to-build-a-simple-neural-network-in-9-lines-of-python-code-cc8f23647ca1

https://github.com/jonasbostoen/simple-neural-network/blob/master/README.md


In [0]:
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt

In [0]:
def sigmoid(x):
  return 1/(1+np.exp(-x))

In [0]:
def sigmoid_derivative(x):
  return x *(1-x)

In [0]:
training_inputs = np.array([[0,0,1],
                            [1,1,1],
                            [1,0,1],
                            [0,1,1]])

In [0]:
training_outputs = np.array([[0,1,1,0]]).T #or training_outputs = np.array([[0],[1],[1],[0]]) 

In [0]:
np.random.seed(1)

In [0]:
synaptic_weights = 2 * np.random.random((3,1)) -1

In [25]:
print('Random Starting synaptic weights:')

Random Starting synaptic weights:


In [26]:
print (synaptic_weights)

[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]


In [30]:
for iteration in range(2000):
  input_layer = training_inputs
  outputs = sigmoid(np.dot(input_layer, synaptic_weights))
  
  error = training_outputs - outputs
  
  adjustments = error * sigmoid_derivative(outputs)
  
  synaptic_weights += np.dot(input_layer.T, adjustments)
  
  print ('Synaptic Weights after training:')
  print (synaptic_weights)

print ('Outputs after training:')
print (outputs)

Synaptic Weights after training:
[[ 5.46838272]
 [-0.21752358]
 [-2.5134548 ]]
Synaptic Weights after training:
[[ 5.47418416]
 [-0.21756436]
 [-2.51635876]]
Synaptic Weights after training:
[[ 5.47995515]
 [-0.21760438]
 [-2.51924772]]
Synaptic Weights after training:
[[ 5.48569601]
 [-0.21764366]
 [-2.52212183]]
Synaptic Weights after training:
[[ 5.49140703]
 [-0.2176822 ]
 [-2.52498124]]
Synaptic Weights after training:
[[ 5.49708852]
 [-0.21772002]
 [-2.52782609]]
Synaptic Weights after training:
[[ 5.50274078]
 [-0.21775715]
 [-2.53065653]]
Synaptic Weights after training:
[[ 5.50836409]
 [-0.21779358]
 [-2.53347269]]
Synaptic Weights after training:
[[ 5.51395875]
 [-0.21782933]
 [-2.53627472]]
Synaptic Weights after training:
[[ 5.51952503]
 [-0.21786442]
 [-2.53906276]]
Synaptic Weights after training:
[[ 5.52506322]
 [-0.21789885]
 [-2.54183693]]
Synaptic Weights after training:
[[ 5.5305736 ]
 [-0.21793264]
 [-2.54459737]]
Synaptic Weights after training:
[[ 5.53605643]
 [-0